### ISSUE TITLE
Compile error for dependencie "group" when trying to build fuzz target

### ISSUE THREAD

**Issue by fu2qa** [signalapp/Signal-Calling-Service#1]
Hello,

thanks for releasing this new interesting service! I wanted to try running the fuzz targets as described in the README, but it failed. I'm not experienced with rust, it seems to be a compile error related to the dependency group v0.9.0. Or is this maybe an error on my side?
I really like, that you ship the service with fuzz targets, nice work!

Signal-Calling-Service$ cargo +nightly fuzz run dtls
   Compiling prost-derive v0.7.0
   Compiling serde v1.0.130
   Compiling pin-project v1.0.8
   Compiling thiserror v1.0.29
   Compiling async-stream v0.3.2
   Compiling rand v0.8.4
   Compiling group v0.9.0
error[E0034]: multiple applicable items in scope
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-derive-0.7.0/src/lib.rs:109:14
    |
109 |             .intersperse(quote!(|));
    |              ^^^^^^^^^^^ multiple `intersperse` found
    |
    = note: candidate #1 is defined in an impl of the trait `Iterator` for the type `Map<I, F>`
    = note: candidate #2 is defined in an impl of the trait `Itertools` for the type `T`
help: disambiguate the associated function for candidate #1
    |
105 ~         let tags = Iterator::intersperse(field
106 +             .tags()
107 +             .into_iter()
108 +             .map(|tag| quote!(#tag)), {
109 +         let mut _s = $crate::__private::TokenStream::new();
110 +         $crate::quote_each_token!(_s $($tt)*);
  ...
help: disambiguate the associated function for candidate #2
    |
105 ~         let tags = Itertools::intersperse(field
106 +             .tags()
107 +             .into_iter()
108 +             .map(|tag| quote!(#tag)), {
109 +         let mut _s = $crate::__private::TokenStream::new();
110 +         $crate::quote_each_token!(_s $($tt)*);
  ...

   Compiling structopt-derive v0.4.16
For more information about this error, try `rustc --explain E0034`.
error: could not compile `prost-derive` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: failed to build fuzz script: "cargo" "build" "--manifest-path" "/home/user/repos/Signal-Calling-Service/fuzz/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "--release" "--bin" "dtls"

**Comment by u32i64** [comment]
The compilation issue seems to point to `prost-derive`. It looks like it's already reported there as well:

- https://github.com/tokio-rs/prost/issues/526

**Comment by jim-signal** [comment]
Thanks @u32i64, that seems to be it. I am able to run using an earlier pinned nightly:

If you haven't already, and replace with your target such as `x86_64-unknown-linux-gnu`:
```
rustup install nightly-2021-06-08
rustup target add x86_64-apple-darwin --toolchain nightly-2021-06-08
```
Then this should work:
```
cargo +nightly-2021-06-08 fuzz run dtls
```
We probably should add a `rust-toolchain` file to help out with this.

**Comment by jrose-signal** [comment]
The fuzz targets still require nightly, but I think we're now far enough ahead that we don't need a *particular* nightly. I'm going to close this for now, since that's true of *all* uses of `cargo fuzz`.
