### ISSUE TITLE
Updated code of SFU for /v2/conference/participants Support ?

### ISSUE THREAD

**Issue by adityaasoleh** [signalapp/Signal-Calling-Service#7]
Hi, i see the sfu code still using /v1/ api instead /v2/ for new version android group calling 
https://github.com/signalapp/Signal-Calling-Service/blob/83eb83a53fc795b75609ce7c8e7c2905f2b7f40f/src/http_server.rs#L10 (https://github.com/signalapp/Signal-Calling-Service/blob/main/src/http_server.rs)

Is there any updated code of SFU code (Signal-Calling-Service) for support /v2/ api for group calling ?  Thanks :)

**Comment by jim-signal** [comment]
Hi @adityaasoleh, we'll update the http_server soon.

**Comment by adityaasoleh** [comment]
Hi @jim-signal Oh okay i see, will glad waiting it, thank you)

**Comment by jim-signal** [comment]
v1.3.4 has the updates to the http_server, hope it helps!

**Comment by adityaasoleh** [comment]
Hi @jim-signal thank you for updating it))
